/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ServicesRouteRouteImport } from './routes/services/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesGovernmentalRouteImport } from './routes/services/governmental'
import { Route as ServicesCommercialRouteImport } from './routes/services/commercial'
import { Route as ServicesArchitecturalRouteImport } from './routes/services/architectural'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRouteRoute = ServicesRouteRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesGovernmentalRoute = ServicesGovernmentalRouteImport.update({
  id: '/governmental',
  path: '/governmental',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesCommercialRoute = ServicesCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesArchitecturalRoute = ServicesArchitecturalRouteImport.update({
  id: '/architectural',
  path: '/architectural',
  getParentRoute: () => ServicesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/architectural': typeof ServicesArchitecturalRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/governmental': typeof ServicesGovernmentalRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/architectural': typeof ServicesArchitecturalRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/governmental': typeof ServicesGovernmentalRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/architectural': typeof ServicesArchitecturalRoute
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/governmental': typeof ServicesGovernmentalRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/about'
    | '/app'
    | '/contact'
    | '/industries'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/services/architectural'
    | '/services/commercial'
    | '/services/governmental'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/industries'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/services/architectural'
    | '/services/commercial'
    | '/services/governmental'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/about'
    | '/app'
    | '/contact'
    | '/industries'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/services/architectural'
    | '/services/commercial'
    | '/services/governmental'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRouteRoute: typeof ServicesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/governmental': {
      id: '/services/governmental'
      path: '/governmental'
      fullPath: '/services/governmental'
      preLoaderRoute: typeof ServicesGovernmentalRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/commercial': {
      id: '/services/commercial'
      path: '/commercial'
      fullPath: '/services/commercial'
      preLoaderRoute: typeof ServicesCommercialRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/architectural': {
      id: '/services/architectural'
      path: '/architectural'
      fullPath: '/services/architectural'
      preLoaderRoute: typeof ServicesArchitecturalRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
  }
}

interface ServicesRouteRouteChildren {
  ServicesArchitecturalRoute: typeof ServicesArchitecturalRoute
  ServicesCommercialRoute: typeof ServicesCommercialRoute
  ServicesGovernmentalRoute: typeof ServicesGovernmentalRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteRouteChildren: ServicesRouteRouteChildren = {
  ServicesArchitecturalRoute: ServicesArchitecturalRoute,
  ServicesCommercialRoute: ServicesCommercialRoute,
  ServicesGovernmentalRoute: ServicesGovernmentalRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteRouteWithChildren = ServicesRouteRoute._addFileChildren(
  ServicesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRouteRoute: ServicesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
